ProductInfo As screen:
    Fill: =RGBA(31, 31, 31, 1)
    LoadingSpinnerColor: =RGBA(255, 200, 61, 1)
    OnVisible: |-
        =ClearCollect(
            ProductImageColl,
            Filter(
                'Product Images',
                Product.'Product Item' = clickproduct.'Product Item'
            )
        );
        Clear(ProdImg);
        Set(
            Count,
            1
        );
        ForAll(
            ProductImageColl,
            Collect(
                ProdImg,
                {
                    id: CountRows(ProdImg) + 1,
                    Image: ThisRecord.'Image Link'
                }
            )
        );
        UpdateContext({currentImg: 1});
        Set(
            Count,
            Count + 1
        );

    Rectangle10_1 As rectangle:
        BorderColor: =RGBA(0, 0, 0, 0)
        BorderStyle: =BorderStyle.None
        BorderThickness: =2
        DisabledFill: =RGBA(166, 166, 166, 1)
        Fill: =RGBA(160, 0, 2, 1)
        FocusedBorderThickness: =4
        Height: =70
        HoverFill: =RGBA(0, 0, 0, 0)
        PressedFill: =RGBA(0, 0, 0, 0)
        Width: =640
        ZIndex: =1

    Rectangle8_1 As rectangle:
        BorderColor: =RGBA(0, 0, 0, 0)
        BorderStyle: =BorderStyle.None
        BorderThickness: =2
        DisabledFill: =RGBA(166, 166, 166, 1)
        Fill: =RGBA(31, 31, 31, 1)
        FocusedBorderThickness: =4
        Height: =2
        HoverFill: =RGBA(255, 200, 61, 1)
        PressedFill: =RGBA(255, 200, 61, 1)
        Width: =640
        Y: =70
        ZIndex: =2

    Icon14_29 As icon.BackArrow:
        BorderColor: =RGBA(109, 109, 109, 1)
        Color: =RGBA(255, 255, 255, 1)
        DisabledBorderColor: =RGBA(0, 0, 0, 0)
        DisabledColor: =RGBA(220, 220, 220, 1)
        DisabledFill: =RGBA(0, 0, 0, 0)
        FocusedBorderThickness: =4
        Height: =43
        HoverBorderColor: =RGBA(0, 0, 0, 0)
        HoverColor: =ColorFade(RGBA(255, 200, 61, 1), 30%)
        HoverFill: =RGBA(0, 0, 0, 0)
        Icon: =Icon.BackArrow
        OnSelect: =Back()
        PressedBorderColor: =RGBA(0, 0, 0, 0)
        PressedColor: =ColorFade(RGBA(255, 200, 61, 1), 30%)
        PressedFill: =RGBA(0, 0, 0, 0)
        Width: =43
        X: =18
        Y: =14
        ZIndex: =3

    Image1_74 As image:
        BorderColor: =RGBA(204, 204, 204, 1)
        BorderStyle: =BorderStyle.None
        BorderThickness: =1
        DisabledBorderColor: =RGBA(0, 0, 0, 0)
        DisabledFill: =RGBA(0, 0, 0, 0)
        FocusedBorderThickness: =4
        Height: =45
        HoverBorderColor: =RGBA(0, 0, 0, 0)
        HoverFill: =RGBA(0, 0, 0, 0)
        Image: =User().Image
        ImagePosition: =ImagePosition.Fill
        OnSelect: =Navigate(Profile)
        PressedBorderColor: =RGBA(0, 0, 0, 0)
        PressedFill: =RGBA(0, 0, 0, 0)
        RadiusBottomLeft: =50
        RadiusBottomRight: =50
        RadiusTopLeft: =50
        RadiusTopRight: =50
        Width: =45
        X: =584
        Y: =13
        ZIndex: =4

    Label1 As label:
        BorderColor: =RGBA(0, 0, 0, 0)
        BorderStyle: =BorderStyle.None
        BorderThickness: =2
        Color: =RGBA(255, 255, 255, 1)
        DisabledBorderColor: =RGBA(0, 0, 0, 0)
        DisabledColor: =RGBA(166, 166, 166, 1)
        FocusedBorderThickness: =4
        Font: =Font.'Segoe UI'
        FontWeight: =FontWeight.Bold
        Height: =52
        Size: =18
        Text: ="Product Info"
        Width: =414
        X: =84
        Y: =6
        ZIndex: =5

    "'Bottom Navigation_84' As 'Bottom Navigation'":
        NavItems: |-
            =Table(
                {
                    Title: If(
                        varAttendance = "end",
                        "End",
                        varAttendance = "start",
                        "Start",
                        varAttendance = "done",
                        "Ended"
                    ),
                    //Title: Start,
                    Screen: If(
                        varAttendance = "start",
                        StartDay,
                        varAttendance = "end",
                        'End day',
                        varAttendance = "done",
                        'Day Ended'
                    ),
                    Icon: CalendarBlank,
                    Active: false
                },
                {
                    Title: "Visits",
                    Screen: Visits,
                    Icon: Waypoint,
                    Active: true
                },
                {
                    Title: "Dashboard",
                    Screen: Home,
                    Icon: Waffle,
                    Active: false
                },
                {
                    Title: "Parties",
                    Screen: 'Customer (Dist)_1',
                    Icon: People,
                    Active: false
                },
                {
                    Title: "Menu",
                    Screen: 'Menu Screen',
                    Icon: Hamburger,
                    Active: false
                }
            )
        Y: =1056
        ZIndex: =21

    Gallery11 As gallery.galleryHorizontal:
        BorderColor: =RGBA(109, 109, 109, 1)
        Height: =280
        Items: |-
            =//Filter('Product Images', Product.'Product Item' = clickproduct.'Product Item')
            ProdImg
        ShowScrollbar: =false
        TemplateSize: =635
        Y: =231
        ZIndex: =22

        Button19_1 As button:
            BorderColor: =RGBA(0, 0, 0, 0)
            Color: =RGBA(31, 31, 31, 1)
            DisabledBorderColor: =RGBA(0, 0, 0, 0)
            DisabledColor: =RGBA(166, 166, 166, 1)
            DisabledFill: =RGBA(255, 255, 255, 1)
            DisplayMode: =DisplayMode.Disabled
            Fill: =RGBA(255, 255, 255, 1)
            FocusedBorderColor: =ColorFade(Self.Fill, 75%)
            Font: =Font.'Segoe UI'
            FontWeight: =FontWeight.Semibold
            Height: =246
            HoverBorderColor: =RGBA(0, 0, 0, 0)
            HoverColor: =RGBA(31, 31, 31, 1)
            HoverFill: =ColorFade(RGBA(255, 200, 61, 1), 10%)
            PressedBorderColor: =ColorFade(RGBA(255, 200, 61, 1), 50%)
            PressedColor: =RGBA(31, 31, 31, 1)
            PressedFill: =ColorFade(RGBA(255, 200, 61, 1), 30%)
            Size: =24
            Text: =""
            Width: =332
            X: =149
            ZIndex: =1

        Image4 As image:
            BorderColor: =RGBA(0, 0, 0, 0)
            BorderStyle: =BorderStyle.None
            BorderThickness: =2
            DisabledBorderColor: =RGBA(0, 0, 0, 0)
            DisabledFill: =RGBA(0, 0, 0, 0)
            FocusedBorderThickness: =4
            Height: =204
            HoverBorderColor: =RGBA(0, 0, 0, 0)
            HoverFill: =RGBA(0, 0, 0, 0)
            Image: |-
                =//Filter('Product Images', Product.'Product Item' = clickproduct.'Product Item')
                
                LookUp(ProdImg, id = currentImg ).Image
            OnSelect: =Select(Parent)
            PressedBorderColor: =RGBA(0, 0, 0, 0)
            PressedFill: =RGBA(0, 0, 0, 0)
            Width: =234
            X: =198
            Y: =18
            ZIndex: =2

        Icon3 As icon.NextArrow:
            BorderColor: =RGBA(109, 109, 109, 1)
            Color: =RGBA(255, 200, 61, 1)
            DisabledBorderColor: =RGBA(0, 0, 0, 0)
            DisabledColor: =RGBA(220, 220, 220, 1)
            DisabledFill: =RGBA(0, 0, 0, 0)
            FocusedBorderThickness: =4
            HoverBorderColor: =RGBA(0, 0, 0, 0)
            HoverColor: =ColorFade(RGBA(255, 200, 61, 1), 30%)
            HoverFill: =RGBA(0, 0, 0, 0)
            Icon: =Icon.NextArrow
            OnSelect: |-
                =//UpdateContext({currentImg:If(currentImg = ThisItem.id, 1, currentImg+1)})
                
                UpdateContext({currentImg:If(Not(currentImg=Max(ProdImg,id)),currentImg+1, 1)})
            PaddingBottom: =10
            PaddingLeft: =10
            PaddingRight: =10
            PaddingTop: =10
            PressedBorderColor: =RGBA(0, 0, 0, 0)
            PressedColor: =ColorFade(RGBA(255, 200, 61, 1), 30%)
            PressedFill: =RGBA(0, 0, 0, 0)
            X: =548
            Y: =88
            ZIndex: =3

        Icon25 As icon.BackArrow:
            BorderColor: =RGBA(109, 109, 109, 1)
            Color: =RGBA(255, 200, 61, 1)
            DisabledBorderColor: =RGBA(0, 0, 0, 0)
            DisabledColor: =RGBA(220, 220, 220, 1)
            DisabledFill: =RGBA(0, 0, 0, 0)
            FocusedBorderThickness: =4
            HoverBorderColor: =RGBA(0, 0, 0, 0)
            HoverColor: =ColorFade(RGBA(255, 200, 61, 1), 30%)
            HoverFill: =RGBA(0, 0, 0, 0)
            Icon: =Icon.BackArrow
            OnSelect: |-
                =//UpdateContext({currentImg:If(currentImg=ThisItem.id,1,currentImg-1)})
                UpdateContext({currentImg:If(currentImg=1,Max(ProdImg,id),currentImg-1)})
            PaddingBottom: =10
            PaddingLeft: =10
            PaddingRight: =10
            PaddingTop: =10
            PressedBorderColor: =RGBA(0, 0, 0, 0)
            PressedColor: =ColorFade(RGBA(255, 200, 61, 1), 30%)
            PressedFill: =RGBA(0, 0, 0, 0)
            X: =16
            Y: =88
            ZIndex: =4

    Label28 As label:
        Align: =Align.Center
        BorderColor: =RGBA(0, 0, 0, 0)
        BorderStyle: =BorderStyle.None
        BorderThickness: =2
        Color: =RGBA(255, 191, 0, 1)
        DisabledBorderColor: =RGBA(0, 0, 0, 0)
        DisabledColor: =RGBA(166, 166, 166, 1)
        FocusedBorderThickness: =4
        Font: =Font.'Segoe UI'
        FontWeight: =FontWeight.Bold
        Height: =87
        Size: =28
        Text: =clickproduct.'Product Name'
        Width: =560
        X: =50
        Y: =100
        ZIndex: =23

    Group12_18 As group:
        Height: =5
        Width: =5
        X: =11
        Y: =20
        ZIndex: =28

        Rectangle5_26 As rectangle:
            BorderColor: =RGBA(0, 0, 0, 0)
            BorderStyle: =BorderStyle.None
            BorderThickness: =2
            DisabledFill: =RGBA(166, 166, 166, 1)
            Fill: =RGBA(99, 105, 139, 1)
            FocusedBorderThickness: =4
            Height: =354
            HoverFill: =
            PressedFill: =
            Width: =639
            X: =1
            Y: =566
            ZIndex: =6

        Label5_420 As label:
            BorderColor: =RGBA(0, 0, 0, 0)
            BorderStyle: =BorderStyle.None
            BorderThickness: =2
            Color: =RGBA(255, 255, 255, 1)
            DisabledBorderColor: =RGBA(0, 0, 0, 0)
            DisabledColor: =RGBA(166, 166, 166, 1)
            FocusedBorderThickness: =4
            Font: =Font.Lato
            FontWeight: =FontWeight.Semibold
            Height: =69
            Size: =17
            Text: ="Product Name"
            Width: =261
            X: =13
            Y: =585
            ZIndex: =7

        Label5_421 As label:
            Align: =Align.Right
            BorderColor: =RGBA(0, 0, 0, 0)
            BorderStyle: =BorderStyle.None
            BorderThickness: =2
            Color: =RGBA(255, 191, 0, 1)
            DisabledBorderColor: =RGBA(0, 0, 0, 0)
            DisabledColor: =RGBA(166, 166, 166, 1)
            FocusedBorderThickness: =4
            Font: =Font.Lato
            FontWeight: =FontWeight.Semibold
            Height: =69
            Size: =19
            Text: =clickproduct.'Product Name'
            Width: =381
            X: =213
            Y: =575
            ZIndex: =8

        Rectangle12_152 As rectangle:
            BorderColor: =RGBA(255, 255, 255, 1)
            BorderStyle: =BorderStyle.Dashed
            BorderThickness: =1
            DisabledFill: =RGBA(166, 166, 166, 1)
            Fill: =RGBA(255, 255, 255, 1)
            FocusedBorderThickness: =4
            Height: =1
            HoverFill: =RGBA(255, 200, 61, 1)
            PressedFill: =RGBA(255, 200, 61, 1)
            Width: =595
            X: =15
            Y: =648
            ZIndex: =9

        Label5_422 As label:
            BorderColor: =RGBA(0, 0, 0, 0)
            BorderStyle: =BorderStyle.None
            BorderThickness: =2
            Color: =RGBA(255, 255, 255, 1)
            DisabledBorderColor: =RGBA(0, 0, 0, 0)
            DisabledColor: =RGBA(166, 166, 166, 1)
            FocusedBorderThickness: =4
            Font: =Font.Lato
            FontWeight: =FontWeight.Semibold
            Height: =69
            Size: =17
            Text: ="HSN Code"
            Width: =261
            X: =13
            Y: =665
            ZIndex: =10

        Label5_423 As label:
            Align: =Align.Right
            BorderColor: =RGBA(0, 0, 0, 0)
            BorderStyle: =BorderStyle.None
            BorderThickness: =2
            Color: =RGBA(255, 191, 0, 1)
            DisabledBorderColor: =RGBA(0, 0, 0, 0)
            DisabledColor: =RGBA(166, 166, 166, 1)
            FocusedBorderThickness: =4
            Font: =Font.Lato
            FontWeight: =FontWeight.Semibold
            Height: =69
            Size: =19
            Text: |-
                =//Text(visitInfo.'Visit Date', "dd mmm yyyy")
                clickproduct.'HSN Code'
            Tooltip: |
                =//Text(clickproduct.'Product Price List'.Price)
                clickproduct.'HSN Code'
            Width: =381
            X: =213
            Y: =665
            ZIndex: =11

        Rectangle12_153 As rectangle:
            BorderColor: =RGBA(255, 255, 255, 1)
            BorderStyle: =BorderStyle.Dashed
            BorderThickness: =1
            DisabledFill: =RGBA(166, 166, 166, 1)
            Fill: =RGBA(255, 200, 61, 1)
            FocusedBorderThickness: =4
            Height: =1
            HoverFill: =RGBA(255, 200, 61, 1)
            PressedFill: =RGBA(255, 200, 61, 1)
            Width: =595
            X: =15
            Y: =729
            ZIndex: =12

        Label5_424 As label:
            BorderColor: =RGBA(0, 0, 0, 0)
            BorderStyle: =BorderStyle.None
            BorderThickness: =2
            Color: =RGBA(255, 255, 255, 1)
            DisabledBorderColor: =RGBA(0, 0, 0, 0)
            DisabledColor: =RGBA(166, 166, 166, 1)
            FocusedBorderThickness: =4
            Font: =Font.Lato
            FontWeight: =FontWeight.Semibold
            Height: =69
            Size: =17
            Text: ="Price per unit"
            Width: =261
            X: =13
            Y: =738
            ZIndex: =13

        Label5_425 As label:
            Align: =Align.Right
            BorderColor: =RGBA(0, 0, 0, 0)
            BorderStyle: =BorderStyle.None
            BorderThickness: =2
            Color: =RGBA(255, 191, 0, 1)
            DisabledBorderColor: =RGBA(0, 0, 0, 0)
            DisabledColor: =RGBA(166, 166, 166, 1)
            FocusedBorderThickness: =4
            Font: =Font.Lato
            FontWeight: =FontWeight.Bold
            Height: =69
            Size: =19
            Text: =Concatenate("₹", LookUp('Product Price List', Product.'Product Item'= clickproduct.'Product Item').Price + 55)
            Width: =381
            X: =213
            Y: =730
            ZIndex: =14

        Rectangle12_154 As rectangle:
            BorderColor: =RGBA(255, 255, 255, 1)
            BorderStyle: =BorderStyle.Dashed
            BorderThickness: =1
            DisabledFill: =RGBA(166, 166, 166, 1)
            Fill: =RGBA(255, 255, 255, 1)
            FocusedBorderThickness: =4
            Height: =1
            HoverFill: =RGBA(255, 200, 61, 1)
            PressedFill: =RGBA(255, 200, 61, 1)
            Width: =595
            X: =15
            Y: =807
            ZIndex: =15

        Label5_426 As label:
            BorderColor: =RGBA(0, 0, 0, 0)
            BorderStyle: =BorderStyle.None
            BorderThickness: =2
            Color: =RGBA(255, 255, 255, 1)
            DisabledBorderColor: =RGBA(0, 0, 0, 0)
            DisabledColor: =RGBA(166, 166, 166, 1)
            FocusedBorderThickness: =4
            Font: =Font.Lato
            FontWeight: =FontWeight.Semibold
            Height: =69
            Size: =17
            Text: ="Category Name"
            Width: =261
            X: =13
            Y: =824
            ZIndex: =16

        Label5_427 As label:
            Align: =Align.Right
            BorderColor: =RGBA(0, 0, 0, 0)
            BorderStyle: =BorderStyle.None
            BorderThickness: =2
            Color: =RGBA(255, 191, 0, 1)
            DisabledBorderColor: =RGBA(0, 0, 0, 0)
            DisabledColor: =RGBA(166, 166, 166, 1)
            FocusedBorderThickness: =4
            Font: =Font.Lato
            FontWeight: =FontWeight.Semibold
            Height: =69
            Size: =19
            Text: |-
                =//visitInfo.status
                clickproduct.PG1.'Category Name'
            Width: =381
            X: =213
            Y: =816
            ZIndex: =17

        Rectangle12_155 As rectangle:
            BorderColor: =RGBA(255, 255, 255, 1)
            BorderStyle: =BorderStyle.Dashed
            BorderThickness: =1
            DisabledFill: =RGBA(166, 166, 166, 1)
            Fill: =RGBA(255, 255, 255, 1)
            FocusedBorderThickness: =4
            Height: =1
            HoverFill: =RGBA(255, 200, 61, 1)
            PressedFill: =RGBA(255, 200, 61, 1)
            Width: =595
            X: =15
            Y: =888
            ZIndex: =18

